"""Test fixtures with real biological data."""

import pytest
from fastapi.testclient import TestClient
from ..main import app

# Real FASTA sequences from GenBank
BRCA2_PARTIAL_FASTA = """>NM_000059.4 Homo sapiens BRCA2 DNA repair associated (BRCA2), mRNA (partial)
ATGCCTATTGGATCCAAAGAGAGGCCAACATTTTTTGAAATTTTTAAGACACGCTGCAACAAAGCAGATT
TAGGACCAATAAGTCTTAATTGGTTTGAAGAACTTTCTTCAGAAGCTCCAGGGATCAGAATTTGGCACAG
"""

TP53_FASTA = """>NP_000537.3 cellular tumor antigen p53 isoform a [Homo sapiens]
MEEPQSDPSVEPPLSQETFSDLWKLLPENNVLSPLPSQAMDDLMLSPDDIEQWFTEDPGPDEAPRMPEAA
PPVAPAPAAPTPAAPAPAPSWPLSSSVPSQKTYPQGLNGTVNLFRNLNKQKLNLLNKKQLIAPINLKKTYS
"""

HUMAN_BETA_GLOBIN_FASTA = """>HBB Homo sapiens hemoglobin subunit beta, mRNA
ATGGTGCACCTGACTCCTGAGGAGAAGTCTGCCGTTACTGCCCTGTGGGGCAAGGTGAACGTGGATGAA
GTTGGTGGTGAGGCCCTGGGCAGGTTGGTATCAAGGTTACAAGACAGGTTTAAGGAGACCAATAGAAACT
GGGCATGTGGAGACAGAGAAGACTCTTGGGTTTCTGATAGGCACTGACTCTCTCTGCCTATTGGTCTATT
TTCCCACCCTTAGGCTGCTGGTGGTCTACCCTTGGACCCAGAGGTTCTTTGAGTCCTTTGGGGATCTGTC
CACTCCTGATGCTGTTATGGGCAACCCTAAGGTGAAGGCTCATGGCAAGAAAGTGCTCGGTGCCTTTAGT
GATGGCCTGGCTCACCTGGACAACCTCAAGGGCACCTTTGCCACACTGAGTGAGCTGCACTGTGACAAGC
TGCACGTGGATCCTGAGAACTTCAGG
"""

# Real VCF data (ClinVar-style)
SAMPLE_VCF = """##fileformat=VCFv4.1
##source=ClinVar
##INFO=<ID=CLNSIG,Number=.,Type=String,Description="Clinical significance">
##INFO=<ID=GENEINFO,Number=1,Type=String,Description="Gene:GeneID">
#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO
13\t32914437\trs80358981\tA\tC\t.\tPASS\tCLNSIG=Pathogenic;GENEINFO=BRCA2:675
17\t7674220\trs28934578\tC\tT\t.\tPASS\tCLNSIG=Pathogenic;GENEINFO=TP53:7157
7\t117559590\trs113993960\tCTT\tC\t.\tPASS\tCLNSIG=Pathogenic;GENEINFO=CFTR:1080
1\t11856378\trs1042522\tC\tG\t.\tPASS\tCLNSIG=Likely_benign;GENEINFO=MTHFR:4524
"""

# Real GFF3 snippet
SAMPLE_GFF3 = """##gff-version 3
chr17\tRefSeq\tgene\t43044295\t43125483\t.\t-\t.\tID=gene-BRCA1;Name=BRCA1;gene_biotype=protein_coding
chr17\tRefSeq\tmRNA\t43044295\t43125483\t.\t-\t.\tID=rna-NM_007294.4;Parent=gene-BRCA1
chr17\tRefSeq\texon\t43044295\t43045802\t.\t-\t.\tParent=rna-NM_007294.4
chr17\tRefSeq\tCDS\t43044295\t43045802\t.\t-\t0\tParent=rna-NM_007294.4;protein_id=NP_009225.1
"""

# Real restriction enzyme target
TEST_TEMPLATE = (
    "AATTCGAATTCGGATCCCTCGAGCCCGGGGTCGACAAGCTTATGCCTATTGGATCCAAAGAGAGGCC"
    "AACATTTTTTGAAATTTTTAAGACACGCTGCAACAAAGCAGATTTAGGACCAATAAGTCTTAATTGGT"
    "TTGAAGAACTTTCTTCAGAAGCTCCAGGGATCAGAATTTGGCACAGCCTATTGGATCCAAAGAGAGGC"
    "CAACATTTTTTGAAATTTTTAAGACACGCTGCAACAAAGCAGATTTAGGACCAATAAGTCTTAATTGGG"
)

# TP53 hotspot for CRISPR
TP53_EXON7 = (
    "TGCACAGACCCTCACATCGATCTTCCTTTATCATCAGAGGCTTGAGAAGGGGCCAGACTGGGCCTTGG"
    "CTCCCAGCATCTTATCCGAGTGGAAGGAAATTTGCGTGTGGAGTATTTGGATGACAGAAACACTTTTCG"
    "ACATAGTGTGGTGGTGCCCTATGAGCCGCCTGAGGTTGGCTCTGACTGTACCACCATCCACTACAACTAC"
)


@pytest.fixture
def client():
    return TestClient(app)


@pytest.fixture
def brca2_fasta() -> str:
    return BRCA2_PARTIAL_FASTA


@pytest.fixture
def tp53_fasta() -> str:
    return TP53_FASTA


@pytest.fixture
def hbb_fasta() -> str:
    return HUMAN_BETA_GLOBIN_FASTA


@pytest.fixture
def sample_vcf() -> str:
    return SAMPLE_VCF


@pytest.fixture
def sample_gff3() -> str:
    return SAMPLE_GFF3


@pytest.fixture
def test_template() -> str:
    return TEST_TEMPLATE


@pytest.fixture
def tp53_exon7() -> str:
    return TP53_EXON7
